# Generated by Django 4.1 on 2025-01-27 19:45

from django.db import migrations

def insert_sample_data(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    
    # Create sample items
    Item.objects.create(name='Item 1', description='Description for Item 1')
    Item.objects.create(name='Item 2', description='Description for Item 2')
    Item.objects.create(name='Item 3', description='Description for Item 3')

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sample_data),
    ]
