apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: k8s-tutorial
        image: public.ecr.aws/n6v5e8w2/tiger4code/k8s-tutorial:latest
        ports:
        - containerPort: 8000 # Django app
        env: 
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef: 
              name: postgres-secrets-file
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: postgres-secrets-file
              key: POSTGRES_PASSWORD
        - name: DB_URL
          valueFrom: 
            configMapKeyRef: 
              name: postgres-config-map
              key: postgres-url
        resources:
          requests:
            memory: "256Mi"  # Minimum memory guaranteed
            cpu: "250m"      # Minimum CPU guaranteed
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "500m"      # Maximum CPU allowed

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # External Service 
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100 # port which will open on k8s Node, via which the webapp will be accessible